# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

default: &default
  adapter: postgresql
  enconding: unicode

development:
  <<: *default
  database: mp01_devp

test:
  <<: *default
  database: mp01_test

production:
  <<: *default
  database: mp01_prod



#default: &default
#  adapter: sqlite3
#  pool: 5
#  timeout: 5000

#development:
#  <<: *default
#  database: db/development.sqlite3

#test:
#  <<: *default
#  database: db/test.sqlite3

#production:
#  <<: *default
#  database: db/production.sqlite3